### ISSUE TITLE
Fix CORS with Accept: header in OPTIONS preflight request

### ISSUE THREAD

**Issue by brucek** [producthunt/producthunt-api#54]
Followon to #26 
So when jQuery ajax sends the OPTIONS preflight request (on Chrome/OSX at least), it is sending

```Access-Control-Request-Headers: authorization, accept```

Which causes the PH API to return a 404:

```
$ curl -H "Origin: http://example.com"  \
   -H "Access-Control-Request-Method: GET" \
   -H "Access-Control-Request-Headers: authorization, accept" \
   -X OPTIONS --verbose    https://api.producthunt.com/v1/posts
* Hostname was NOT found in DNS cache
*   Trying 50.19.247.175...
* Connected to api.producthunt.com (50.19.247.175) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.producthunt.com
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> OPTIONS /v1/posts HTTP/1.1
> User-Agent: curl/7.37.1
> Host: api.producthunt.com
> Accept: */*
> Origin: http://example.com
> Access-Control-Request-Method: GET
> Access-Control-Request-Headers: authorization, accept
> 
< HTTP/1.1 404 Not Found
* Server Cowboy is not blacklisted
< Server: Cowboy
< Connection: keep-alive
< Content-Type: text/html; charset=utf-8
< X-Request-Id: ae057d3a-5488-4aaf-9051-e6dfe6affd6c
< X-Runtime: 0.005681
< Date: Thu, 23 Apr 2015 01:16:19 GMT
< X-Rack-Cache: invalidate, pass
< Vary: Origin
< Content-Length: 461
< Via: 1.1 vegur
[...]
```

It works fine if the `Access-Control-Request-Headers` only has `authorization` and not `accept`.  Can you allow the Accept header as well?

This seems difficult/impossible to remove as per http://stackoverflow.com/questions/18491368/is-there-any-way-to-remove-ajax-headers-set-by-setrequestheader

**Comment by lfittl** [comment]
Thanks, we'll release a fix for this shortly.

**Comment by lfittl** [comment]
This has been fixed - please re-open if you still run into issues.

**Comment by doplumi** [comment]
`fetch`ing still gets a 404 on the `OPTIONS` pre-flight request, when using the Fetch API.

Here is a snippet you can past into [jsbin.com](jsbin.com) to try. Be sure to fill in your client_id and client_secret:

```js
return fetch("https://api.producthunt.com/v1/oauth/token", {
    method: "post",
    headers: new Headers({
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    }),
    body: JSON.stringify({
      client_id: "xyz",
      client_secret: "xyz",
      grant_type: "client_credentials"
    });
})
```

Fwiw, here are the headers sent with the failing pre-flight:
```
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8,it;q=0.6
Access-Control-Request-Headers:content-type
Access-Control-Request-Method:POST
Cache-Control:no-cache
Connection:keep-alive
Host:api.producthunt.com
Origin:http://localhost:8080
Pragma:no-cache
Referer:http://localhost:8080/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.28 Safari/537.36
```

**Comment by jenil** [comment]
anyone managed to fix this?
